spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jwt:
    secret: ${JWT_SECRET}
    access-token-expire: 60 #minute
    refresh-token-expire: 20160 #minute

  data:
    redis:
      host: ${REDIS_HOST}
